# Generated by Django 4.1rc1 on 2023-03-02 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('coupon_id', models.CharField(max_length=16, unique=True, verbose_name='쿠폰아이디')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='이름')),
                ('description', models.TextField(verbose_name='내용')),
                ('min_price', models.BigIntegerField(blank=True, null=True, verbose_name='최소금액')),
                ('discount', models.IntegerField(verbose_name='할인')),
                ('is_issued', models.BooleanField(default=False, verbose_name='발급여부')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용여부')),
                ('coupon_cate', models.CharField(choices=[('Fix', '정률쿠폰'), ('Flat', '정액쿠폰')], max_length=20, verbose_name='쿠폰종류')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name_plural': '쿠폰',
            },
        ),
    ]
