# Generated by Django 4.1rc1 on 2023-02-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
            ],
            options={
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clothes', to='clothes.categories', verbose_name='카테고리')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='markets.market', verbose_name='사이트')),
            ],
            options={
                'verbose_name_plural': '상품',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('description', models.TextField(verbose_name='설명')),
                ('stock', models.IntegerField(verbose_name='재고')),
                ('colors', models.CharField(max_length=20, verbose_name='색상')),
                ('size', models.CharField(max_length=20, verbose_name='사이즈')),
                ('is_sold_out', models.BooleanField(default=False, verbose_name='품절여부')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='clothes.categories', verbose_name='카테고리')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='clothes.clothes')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='markets.market', verbose_name='사이트')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=30)),
                ('file', models.ImageField(upload_to='product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='clothes.clothes')),
            ],
            options={
                'verbose_name_plural': '상품 사진',
            },
        ),
    ]
