# Generated by Django 4.1rc1 on 2023-01-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='markets.market', verbose_name='사이트'),
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='clothes.clothes'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clothes', to='clothes.categories', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='markets.market', verbose_name='사이트'),
        ),
    ]
