# Generated by Django 4.1rc1 on 2023-01-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
