# Generated by Django 4.1rc1 on 2023-01-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_product_created_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='clothes.clothes'),
        ),
    ]
