# Generated by Django 4.1rc1 on 2023-03-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_paycate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
